# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/msinclair94/workspace/checkers

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/msinclair94/workspace/checkers

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/msinclair94/workspace/checkers/CMakeFiles /home/msinclair94/workspace/checkers/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/msinclair94/workspace/checkers/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named draughts

# Build rule for target.
draughts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 draughts
.PHONY : draughts

# fast build rule for target.
draughts/fast:
	$(MAKE) -f CMakeFiles/draughts.dir/build.make CMakeFiles/draughts.dir/build
.PHONY : draughts/fast

#=============================================================================
# Target rules for targets named visual

# Build rule for target.
visual: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 visual
.PHONY : visual

# fast build rule for target.
visual/fast:
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/build
.PHONY : visual/fast

DrawGame.o: DrawGame.cpp.o
.PHONY : DrawGame.o

# target to build an object file
DrawGame.cpp.o:
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/DrawGame.cpp.o
.PHONY : DrawGame.cpp.o

DrawGame.i: DrawGame.cpp.i
.PHONY : DrawGame.i

# target to preprocess a source file
DrawGame.cpp.i:
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/DrawGame.cpp.i
.PHONY : DrawGame.cpp.i

DrawGame.s: DrawGame.cpp.s
.PHONY : DrawGame.s

# target to generate assembly for a file
DrawGame.cpp.s:
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/DrawGame.cpp.s
.PHONY : DrawGame.cpp.s

GameWindow.o: GameWindow.cpp.o
.PHONY : GameWindow.o

# target to build an object file
GameWindow.cpp.o:
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/GameWindow.cpp.o
.PHONY : GameWindow.cpp.o

GameWindow.i: GameWindow.cpp.i
.PHONY : GameWindow.i

# target to preprocess a source file
GameWindow.cpp.i:
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/GameWindow.cpp.i
.PHONY : GameWindow.cpp.i

GameWindow.s: GameWindow.cpp.s
.PHONY : GameWindow.s

# target to generate assembly for a file
GameWindow.cpp.s:
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/GameWindow.cpp.s
.PHONY : GameWindow.cpp.s

bst.o: bst.cpp.o
.PHONY : bst.o

# target to build an object file
bst.cpp.o:
	$(MAKE) -f CMakeFiles/draughts.dir/build.make CMakeFiles/draughts.dir/bst.cpp.o
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/bst.cpp.o
.PHONY : bst.cpp.o

bst.i: bst.cpp.i
.PHONY : bst.i

# target to preprocess a source file
bst.cpp.i:
	$(MAKE) -f CMakeFiles/draughts.dir/build.make CMakeFiles/draughts.dir/bst.cpp.i
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/bst.cpp.i
.PHONY : bst.cpp.i

bst.s: bst.cpp.s
.PHONY : bst.s

# target to generate assembly for a file
bst.cpp.s:
	$(MAKE) -f CMakeFiles/draughts.dir/build.make CMakeFiles/draughts.dir/bst.cpp.s
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/bst.cpp.s
.PHONY : bst.cpp.s

checkers.o: checkers.cpp.o
.PHONY : checkers.o

# target to build an object file
checkers.cpp.o:
	$(MAKE) -f CMakeFiles/draughts.dir/build.make CMakeFiles/draughts.dir/checkers.cpp.o
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/checkers.cpp.o
.PHONY : checkers.cpp.o

checkers.i: checkers.cpp.i
.PHONY : checkers.i

# target to preprocess a source file
checkers.cpp.i:
	$(MAKE) -f CMakeFiles/draughts.dir/build.make CMakeFiles/draughts.dir/checkers.cpp.i
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/checkers.cpp.i
.PHONY : checkers.cpp.i

checkers.s: checkers.cpp.s
.PHONY : checkers.s

# target to generate assembly for a file
checkers.cpp.s:
	$(MAKE) -f CMakeFiles/draughts.dir/build.make CMakeFiles/draughts.dir/checkers.cpp.s
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/checkers.cpp.s
.PHONY : checkers.cpp.s

game.o: game.cpp.o
.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) -f CMakeFiles/draughts.dir/build.make CMakeFiles/draughts.dir/game.cpp.o
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i
.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/draughts.dir/build.make CMakeFiles/draughts.dir/game.cpp.i
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s
.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/draughts.dir/build.make CMakeFiles/draughts.dir/game.cpp.s
	$(MAKE) -f CMakeFiles/visual.dir/build.make CMakeFiles/visual.dir/game.cpp.s
.PHONY : game.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/draughts.dir/build.make CMakeFiles/draughts.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/draughts.dir/build.make CMakeFiles/draughts.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/draughts.dir/build.make CMakeFiles/draughts.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... draughts"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... visual"
	@echo "... DrawGame.o"
	@echo "... DrawGame.i"
	@echo "... DrawGame.s"
	@echo "... GameWindow.o"
	@echo "... GameWindow.i"
	@echo "... GameWindow.s"
	@echo "... bst.o"
	@echo "... bst.i"
	@echo "... bst.s"
	@echo "... checkers.o"
	@echo "... checkers.i"
	@echo "... checkers.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

